### ISSUE TITLE
Packageing failure of the outside shipping box

### ISSUE THREAD

**Issue by steveruss** [Robo3D/Customer_Feedback#2]
Recieved my first R2 a week ago from Amazon via UPS and the box arrived in this condition:

![firstshipment reduced](https://user-images.githubusercontent.com/6875909/32844839-8946d76a-c9e0-11e7-91a3-a8f6f1ffb781.JPG)

It was decided based on the condition of the first one that a replacement would be sent out.

I received the new R2 yesterday via FedEx...and the outside shipping box failed in the same manor.

![secondshipment reduced](https://user-images.githubusercontent.com/6875909/32844972-db633a7a-c9e0-11e7-8c44-3235522291db.JPG)

For those of you who don't know...these boxes are shipped to, and stored in, manufacturing flattened out on a pallet, then assembled (glued) in manufacturing as needed.

The glue is failing and needs to be addressed.

Notice that the edges taped with clear pack tape survived the abuse from both carriers.

As a workaround, until a more infallible glue is found and tested, extra pack tape on this seam should get you through.

Kudos to the person who takes the initiative to relay this information the the VP of Manufacturing.

**Comment by peries** [comment]
thank you @steveruss 
this report has been passed onto @jerryrobo3d
