### ISSUE TITLE
R2: Fine Tune Offset Wizard instructions "Ass Backwards"

### ISSUE THREAD

**Issue by steveruss** [Robo3D/Customer_Feedback#8]
R2 firmware 1.8.1-r2.1

assbackwards definition: adverb, Slang: Sometimes Vulgar.
1. in an order or way reverse from the usual:
You've sewn the sleeve on assbackwards.
2. in a manner incongruously or preposterously counter to what is customary, probable, or feasible:
The plan fell apart because everything leading up to it was handled assbackwards.

So...it's time to run that Fine Tune Offset Wizard

a) from the R2 touchpad choose Utilities/Wizards/Fine Tune offset.
b) on the next view touch OK.
c) select material. (this is kinda stupid because I used the Filament Change wizard which asked me the same question. Why doesn't this R2 remember which Filament is loaded? ) So go ahead and select the loaded material again :-(
d) Choose a starting corner. (hint: doesn't matter)
e) after the printer is prepared...touch OK on the next view.

Which should bring you to this picture...titled Instructions:

![finetunewizard1](https://user-images.githubusercontent.com/6875909/33775576-127422a4-dbfc-11e7-8af0-71e1da6a65c6.JPG)

Look at this picture very carefully (as nobody else EVER has).

The top row shows a rounded extrusion but the error text on the left side says it's because the "Bed is too high"

The middle row is properly stated how it should be...a nice flat shape...the width of the nozzle head.

The bottom row shows the print head smashed onto the build plate but the error text on the left side says this head-on-plate consequence is because the "**Bed is too low**" WHAT?

f) right arrow to the next view and get these options:

![finetunewizard2](https://user-images.githubusercontent.com/6875909/33775596-1dbd428a-dbfc-11e7-9454-7639afdb8a26.JPG)

So...if my first test shows a mashed flat extrusion and the picture said it is because the bed is too low. It's pretty clear that I should use the Bed Up button and see if that fixes the problem.

Put your Idiot hat on for this. An Idiot would want to follow instructions explicitly. 

A) Print head is smashed into the print bed so "Bed Up" a bit. Then press the "Test Offset button and scrutinize the results.

Imagine for just a moment what that would do!

B) OH...still smashed looking.

C) Repeat steps A and B again and again and again until either 1) something gets damaged or 2) you realize the instructions are Bogus and Ass Backwards!

ABSOLUTELY UNBELIEVABLE...

1) engineering didn't catch this considering the number of times they must have gone through these views.
2) quality assurance didn't catch it. (easy to answer this one)
3) NO ONE else at ROBO caught this glaring mistake.

**Comment by OutsourcedGuru** [comment]
Here, here.

QA should test all wizards and actually read the screens.  (Note the "shutting down" wizard that indicates that you should pull the plug when the screen "goes black" and the screen clearly goes _white_ instead.)

**Comment by peries** [comment]
thank you @steveruss 
we've implemented this change in the next update

**Comment by peries** [comment]
and same thing for your comment @OutsourcedGuru
